=== vladpetrov/task-4-XML-XSD/src/resources/Hangar.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.epam.by/Hangar"
	xmlns="http://www.epam.by/Hangar">
	<xs:element name="hangar">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="plane" type="Plane" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="Plane">
		<xs:sequence>
			<xs:element name="origin" type="Origin"/>
			<xs:element name="chars" type="Chars"/>
			<xs:element name="parameters" type="Parameters"/>
			<xs:element name="price" type="Price"/>
		</xs:sequence>
		<xs:attribute name="model" type="xs:ID" use="required"/>
	</xs:complexType>
	<xs:simpleType name="Origin">
		<xs:restriction base="xs:string">
			<xs:pattern value="[A-Z].*"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="Chars">
		<xs:sequence>
			<xs:element name="type" type="Type"/>
			<xs:element name="seats">
				<xs:simpleType>
    				<xs:restriction base="xs:integer">
      					<xs:minInclusive value="0"/>
      					<xs:maxInclusive value="8"/>
    				</xs:restriction>
  				</xs:simpleType>
			</xs:element>
			<xs:element name="radar" type="xs:boolean"/>
			<xs:element name="ammunition" type="Ammunition" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="Type">
		<xs:restriction base="xs:string">
			<xs:enumeration value="fighter"/>
			<xs:enumeration value="bomber"/>
			<xs:enumeration value="UAV"/>
			<xs:enumeration value="transporter"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="Ammunition">
		<xs:sequence>
			<xs:element name="rockets" type="xs:integer"/>
			<xs:element name="machine_guns" type="xs:integer"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Parameters">
		<xs:sequence>
			<xs:element name="length" type="xs:integer"/>
			<xs:element name="width" type="xs:integer"/>
			<xs:element name="height" type="xs:integer"/>
		</xs:sequence>
		<xs:attribute name="measuring" type="Measuring" use="required"/>
	</xs:complexType>
	<xs:simpleType name="Measuring">
		<xs:restriction base="xs:string">
			<xs:enumeration value="m"/>
			<xs:enumeration value="ft"/>
			<xs:enumeration value="inc"/>
			<xs:enumeration value="cm"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="Price">
		<xs:simpleContent>
			<xs:extension base="xs:integer">
				<xs:attribute name="currency" use="optional" type="xs:string" fixed="thaler"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:schema>

=== vladpetrov/task-4-XML-XSD/src/resources/Hangar.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="Hangar.xsl"?>
<han:hangar xmlns:han="http://www.epam.by/Hangar"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://www.epam.by/Hangar Hangar.xsd">
	<plane model="Rus-1">
		<origin>Russia</origin>
		<chars>
			<type>fighter</type>
			<seats>1</seats>
			<radar>true</radar>
			<ammunition>
				<rockets>5</rockets>
				<machine_guns>2</machine_guns>
			</ammunition>
		</chars>
		<parameters measuring="m">
			<length>20</length>
			<width>15</width>
			<height>6</height>
		</parameters>
		<price currency="thaler">1000000</price>
	</plane>

	<plane model="US-3">
		<origin>USA</origin>
		<chars>
			<type>bomber</type>
			<seats>2</seats>
			<radar>true</radar>
			<ammunition>
				<rockets>10</rockets>
				<machine_guns>4</machine_guns>
			</ammunition>
		</chars>
		<parameters measuring="m">
			<length>30</length>
			<width>23</width>
			<height>8</height>
		</parameters>
		<price currency="thaler">1200000</price>
	</plane>
	<plane model="Chi-5">
		<origin>China</origin>
		<chars>
			<type>UAV</type>
			<seats>0</seats>
			<radar>true</radar>
		</chars>
		<parameters measuring="m">
			<length>10</length>
			<width>5</width>
			<height>3</height>
		</parameters>
		<price currency="thaler">500000</price>
	</plane>
</han:hangar>
